# Telegram Bot Configuration
telegram.bot.token=YOUR_BOT_TOKEN
telegram.bot.username=YOUR_BOT_USERNAME
telegram.channel.id=YOUR_CHANNEL_ID

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/system_monitor_db
spring.datasource.username=your_username
spring.datasource.password=your_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
