# Spring Boot Configuration
spring.threads.virtual.enabled=true

# Telegram Bot Configuration
telegram.bot.token=YOUR_BOT_TOKEN
telegram.bot.username=YOUR_BOT_USERNAME

# PostgreSQL Database Configuration
# These settings are configured to work with the provided docker-compose.yml
spring.datasource.url=jdbc:postgresql://localhost:5432/monitor_db
spring.datasource.username=monitor_user
spring.datasource.password=strong_password
spring.jpa.hibernate.ddl-auto=validate # Use 'validate' because Flyway handles the schema

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
